services:
  postgres:
    image: postgres:15.4
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
